import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CssBaseline, Grid } from "@mui/material";
import TopBar from "./shared/topBar/topBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CssBaseline enableColorScheme />
        <Grid className="p-4" container spacing={2}>
          <Grid size={12}>
            <TopBar />
          </Grid>
          <Grid size={1}></Grid>
          <Grid container size={10}>
            {children}
          </Grid>
          <Grid size={1}></Grid>
        </Grid>
      </body>
    </html>
  );
}
