# Use an official lightweight Python image
FROM python:3.9-slim  

# Set the working directory
WORKDIR /app  

# Copy project files into the container
COPY . /app  

# Install dependencies
RUN pip install -r requirements.txt  

# Expose port 3002 for Flask
EXPOSE 3002  

# Command to run the app
CMD ["python", "main.py"]